CREATE TABLE CUSTOMER (
  C_CODE VARCHAR2(4) PRIMARY KEY,
  C_NAME VARCHAR2(30),
  C_CEO VARCHAR2(12),
  C_ADDR VARCHAR2(100),
  C_PHONE VARCHAR2(13)
);

CREATE TABLE PRODUCT (
  P_CODE CHAR(3) PRIMARY KEY,
  P_NAME VARCHAR2(30),
  P_COST NUMBER,
  P_GROUP VARCHAR2(30)
);

CREATE TABLE STOCK (
  P_CODE CHAR(3) PRIMARY KEY,
  S_PTY NUMBER,
  S_LASTDATE DATE
);

DESC CUSTOMER;
DESC PRODUCT;
DESC STOCK;

INSERT INTO PRODUCT VALUES ('202', '유선마우스',180000, '마우스');
INSERT INTO PRODUCT VALUES ('301', '무선키보드',8000, '키보드');
INSERT INTO PRODUCT VALUES ('302', '유선키보드',22000, '키보드');
INSERT INTO PRODUCT VALUES ('401', '2채널 스피커',10000, '스피커');
INSERT INTO PRODUCT VALUES ('402', '5.1채널 스피커',120000, '스피커');

SELECT * FROM PRODUCT;





