-- 9-1.
SELECT SAL FROM EMP WHERE ENAME = 'JONES';
-- 2
SELECT * FROM EMP WHERE SAL > 2975;
-- 3. 서브쿼리로 JONES의 급여보다 높은 급여를 받는 사원 정보 출력
SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'JONES');
-- 1분복습
-- ALLEN 의 추가수당보다 많은 추가 수당을 받는 사원
SELECT * FROM EMP WHERE COMM > (SELECT COMM FROM EMP WHERE ENAME = 'ALLEN');
-- 9-4 날짜형 서브쿼리
SELECT * FROM EMP WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME='SCOTT');
-- 5.
SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
  WHERE E.DEPTNO = D.DETPNO 
    AND E.DEPTNO = 20
    AND E.SAL > (SELECT AVG(SAL) FROM EMP);
-- 6. 
SELECT * FROM EMP WHERE DEPTNO IN(20, 30);
-- 7. 부서별 최고 급여와 동일한 급여를 받는 사원
SELECT * FROM EMP
  WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);
-- 9.
SELECT * FROM EMP
  WHERE SAL = ANY (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);
-- 10.
SELECT * FROM EMP
  WHERE SAL = SOME (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);
-- 13. 30번 부서 사원들의 최소 급여보다 많은 급여를 받는 사원
SELECT * FROM EMP
  WHERE SAL > (SELECT MIN(SAL) FROM EMP WHERE DEPTNO=30);
-- 15. 30번 부서 사원들의 최대급여 보다 더 많은 급여를 받는 사원
SELECT * FROM EMP
  WHERE SAL > ALL (SELECT SAL FROM EMP WHERE DEPTNO=30);

-- 18. 다중열 서브쿼리
SELECT * FROM EMP
  WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO);

-- 19 인라인 뷰 : FROM 절에서 서브쿼리 사용하기
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
    FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10,
         (SELECT * FROM DEPT) D
  WHERE E10.DEPTNO = D.DEPTNO;

-- WITH 절 사용하기
WITH
E10 AS (SELECT * FROM EMP WHERE DEPTNO = 10),
D   AS (SELECT * FROM DEPT)
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
  FROM E10, D
WHERE E10.DEPTNO = D.DEPTNO;

-- SELECT절에서 서브쿼리 사용하기
SELECT EMPNO, ENAME, JOB, SAL,
      (SELECT GRADE FROM SALGRADE WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE,
      DEPTNO,
      (SELECT DNAME FROM DEPT WHERE E.DEPTNO = DEPT.DEPTNO) AS DNAME
  FROM EMP E;


-- P.262
-- Q1. ALLEN과 같은 직책인 사원들의 사원정보, 부서정보 출력
SELECT JOB, EMPNO, ENAME, SAL, DEPTNO, DNAME
    FROM EMP NATURAL JOIN DEPT
  WHERE JOB IN (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN');
  
-- Q2. 전체 사원의 평균급여보다 높은 급여를 받는 사원들의
-- 사원정보, 부서정보, 급여등급 정보를 출력
SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL, S.GRADE
    FROM EMP E, DEPT D, SALGRADE S
  WHERE E.DEPTNO = D.DEPTNO
    AND E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND E.SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY E.SAL DESC, E.EMPNO;

-- Q3. 10번 부서에 근무하는 사원 중 30번 부서에는 존재하지 않는 직책을 가진
-- 사원들의 사원 정보, 부서정보를 출력
SELECT EMPNO, ENAME, JOB, DEPTNO, DNAME, LOC
    FROM EMP NATURAL JOIN DEPT
  WHERE DEPTNO = 10
    AND JOB NOT IN (SELECT JOB FROM EMP WHERE DEPTNO = 30);
    
-- Q4 SALESMAN 직책 사람들의 최고 급여보다 높은 급여를 받는 사원들의 사원정보, 급여등급 출력
-- 단일행 사용
SELECT EMPNO, ENAME, SAL, GRADE
    FROM EMP, SALGRADE
  WHERE SAL BETWEEN LOSAL AND HISAL
    AND SAL > ( SELECT MAX(SAL) FROM EMP WHERE JOB='SALESMAN')
ORDER BY EMPNO;
-- 다중행
SELECT EMPNO, ENAME, SAL, GRADE
    FROM EMP, SALGRADE
  WHERE SAL BETWEEN LOSAL AND HISAL
    AND SAL > ALL ( SELECT SAL FROM EMP WHERE JOB='SALESMAN')
ORDER BY EMPNO;



-- p.287
CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP;
CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;

-- Q1
SELECT * FROM CHAP10HW_DEPT;
INSERT INTO CHAP10HW_DEPT VALUES (50, 'ORACLE', 'BUSAN');
INSERT INTO CHAP10HW_DEPT VALUES (60, 'SQL', 'ILSAN');
INSERT INTO CHAP10HW_DEPT VALUES (70, 'SELECT', 'INCHEON');
INSERT INTO CHAP10HW_DEPT VALUES (80, 'DML', 'BUNDANG');

-- Q2
INSERT INTO CHAP10HW_EMP 
  VALUES (7201, 'TEST_USER1', 'MANAGER', 7788, TO_DATE('2016-01-02', 'YYYY-MM-DD'), 4500, NULL, 50);
INSERT INTO CHAP10HW_EMP
  VALUES(7202, 'TEST_USER2', 'CLERK', 7201, TO_DATE('2016-02-21', 'YYYY-MM-DD'), 1800, NULL, 50);
INSERT INTO CHAP10HW_EMP
  VALUES(7203, 'TEST_USER3', 'ANALYST', 7201, TO_DATE('2016-04-11', 'YYYY-MM-DD'), 3400, NULL, 60);
INSERT INTO CHAP10HW_EMP
  VALUES(7204, 'TEST_USER4', 'SALESMAN', 7201, TO_DATE('2016-05-31', 'YYYY-MM-DD'), 2700, 300, 60);
INSERT INTO CHAP10HW_EMP
  VALUES(7205, 'TEST_USER5', 'CLERK', 7201, TO_DATE('2016-07-20', 'YYYY-MM-DD'), 2600, NULL, 70);
INSERT INTO CHAP10HW_EMP
  VALUES(7206, 'TEST_USER6', 'CLERK', 7201, TO_DATE('2016-09-08', 'YYYY-MM-DD'), 2600, NULL, 70);
INSERT INTO CHAP10HW_EMP
  VALUES(7207, 'TEST_USER7', 'LECTURER', 7201, TO_DATE('2016-10-28', 'YYYY-MM-DD'), 2300, NULL, 80);
INSERT INTO CHAP10HW_EMP
  VALUES(7208, 'TEST_USER8', 'STUDENT', 7201, TO_DATE('2018-03-09', 'YYYY-MM-DD'), 1200, NULL, 80);
  
-- Q3
-- 50번 부서에서 근무하는 사원들의 평균 급여보다 많은 급여를 받고 있는 사원들을 70번 부서로 이동
UPDATE CHAP10HW_EMP
    SET DEPTNO = 70
  WHERE SAL > (SELECT AVG(SAL) FROM CHAP10HW_EMP WHERE DEPTNO=50);
  
SELECT * FROM CHAP10HW_EMP ORDER BY DEPTNO;

-- Q4
-- 60번 부서 사원 중 입사일이 가장 빠른 사원보다 늦게 입사한 사원의 급여 10% 인상, 80번으로 이동
UPDATE CHAP10HW_EMP
    SET SAL = SAL*1.1, DEPTNO = 80
  WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM CHAP10HW_EMP WHERE DEPTNO = 60);
  
-- Q5
-- 급여등급이 5인 사원을 삭제하시오
DELETE FROM CHAP10HW_EMP
  WHERE EMPNO IN (SELECT EMPNO
                    FROM CHAP10HW_EMP E, CHAP10HW_SALGRADE S
                  WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                    AND S.GRADE = 5);
