CREATE OR REPLACE FUNCTION TEST6
  (V_ENR_GRADE IN NUMBER)
RETURN CHAR   -- 함수를 실행한 후 반환값에 대한 자료형 선언

IS
  ENR_SCORE CHAR;
  
BEGIN
    IF    V_ENR_GRADE >= 90 THEN ENR_SCORE := 'A';
    ELSIF V_ENR_GRADE >= 80 THEN ENR_SCORE := 'B';
    ELSIF V_ENR_GRADE >= 70 THEN ENR_SCORE := 'C';
    ELSE ENR_SCORE := 'F';
  END IF;
  RETURN (ENR_SCORE);
END TEST6;
/
-- 함수는 반환값이 있다 이를 위해 변수를 선언하고 있다.
VARIABLE D_SCORE CHAR;
EXECUTE :D_SCORE := TEST6(95);

PRINT D_SCORE;

SELECT * FROM ENROL WHERE STU_NO = '20131001';
  
-- SQL 에서 함수 사용하기
SELECT ENR_GRADE, TEST6(ENR_GRADE) AS 점수
    FROM ENROL
  WHERE STU_NO = '20131001';
  
  
-- P.519 Q2
CREATE OR REPLACE FUNCTION FUNC_DATE_KOR
(
  DD IN DATE
)
RETURN VARCHAR2

IS
BEGIN
  RETURN (TO_CHAR(DD, 'YYYY"년" MM"월" DD"일"'));
END FUNC_DATE_KOR;
/


SELECT ENAME, FUNC_DATE_KOR(HIREDATE) AS HIREDATE
  FROM  EMP WHERE EMPNO = 7369;

