-- JOIN
-- 부서번호가 같을 때 테이블을 조인해서 출력하겠다
SELECT * FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO;
-- STUDENT, ENROL 합쳐서 다 출력
SELECT STUDENT.STU_NO, STU_NAME, STU_DEPT
FROM STUDENT, ENROL WHERE STUDENT.STU_NO = ENROL.STU_NO;
-- NATURAL JOIN
SELECT STU_NO, STU_NAME, ENR_GRADE FROM STUDENT NATURAL JOIN ENROL;
-- JOIN ~ USING
SELECT STU_NO, STU_NAME, ENR_GRADE 
FROM STUDENT JOIN ENROL USING(STU_NO);
-- 
select student.stu_no, stu_name, stu_dept, enr_grade from student join enrol on student.stu_no=enrol.stu_no;
-- 학생테이블과 수강테이블을 NATURAL JOIN 하시오
SELECT * FROM STUDENT NATURAL JOIN ENROL;
-- 과목이름과 학번, 점수를 검색하시오 (N.J)
SELECT SUB_NAME, STU_NO, ENR_GRADE
    FROM SUBJECT 
    NATURAL JOIN ENROL;
-- -- 과목이름과 학번, 점수를 검색하시오 (JOIN ~ USING)
SELECT SUB_NAME, STU_NO, ENR_GRADE
    FROM SUBJECT 
    JOIN ENROL USING(SUB_NO);

-- 점수가 70점 이상인 학생 이름을 검색 E.J
SELECT STU_NAME
    FROM STUDENT, ENROL
WHERE STUDENT.STU_NO = ENROL.STU_NO
    AND ENR_GRADE >= 70;
-- 점수가 60점 이상인 학생 이름 J.U
SELECT STU_NAME
    FROM STUDENT
    JOIN ENROL USING (STU_NO)
WHERE ENR_GRADE >= 60;
-- 70점 이하인 학생
SELECT STU_NAME
    FROM STUDENT
    NATURAL JOIN ENROL
WHERE ENR_GRADE <= 70;
-- 강종영 교수가 강의하는 과목을 수강하는 학생 이름 (이큐조인)
SELECT STU_NAME
    FROM STUDENT, SUBJECT, ENROL
WHERE STUDENT.STU_NO=ENROL.STU_NO
    AND ENROL.SUB_NO=SUBJECT.SUB_NO
    AND SUB_PROF='강종영';
