-- 4-1,2,3
DESC EMP;
DESC DEPT;
DESC SALGRADE;
-- 4-4
SELECT * FROM EMP;
-- 4-5
SELECT EMPNO, ENAME, DEPTNO FROM EMP;
-- 4-6
SELECT DISTINCT DEPTNO FROM EMP;
-- 4-7
SELECT DISTINCT JOB, DEPTNO FROM EMP;
-- 4-8
SELECT ALL JOB, DEPTNO FROM EMP;
-- 4-9
SELECT ENAME, SAL, SAL*12+COMM, COMM FROM EMP;
-- 4-10 곱하기 사용하지 않고 연간 총 수입 구하기
SELECT ENAME, SAL, SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+COMM AS 연봉, COMM
FROM EMP;
--4-11
SELECT ENAME, SAL, SAL*12+COMM AS ANNSAL, COMM FROM EMP;
-- 4-12 급여기준으로 오름차순 정렬
SELECT * FROM EMP ORDER BY SAL;
-- 4-13 급여기준으로 내림차순 정렬
SELECT * FROM EMP ORDER BY SAL DESC;
-- 4-14 부서번호(오름차순)와 급여(내림차순)로 정렬
SELECT* FROM EMP ORDER BY DEPTNO, SAL DESC;


-- P. 157~166
-- 6-31 숫자와 문자열 더하여 출력
SELECT EMPNO, ENAME, EMPNO + '500' FROM EMP WHERE ENAME = 'SCOTT';
-- 6-32
SELECT 'ABCD'+EMPNO, EMPNO FROM ENP WHERE ENAME='SCOTT';
-- 오류 발생
-- 6-33
SELECT TO_CHAR(SYSDATE, 'YY/MM/DD HH12:MI:SS') AS 현재날짜시간 FROM DUAL;
-- 6-34 월과 요일을 다양한 형식으로
SELECT SYSDATE,
    TO_CHAR(SYSDATE, 'MM') AS MM,
    TO_CHAR(SYSDATE, 'MON') AS MON,
    TO_CHAR(SYSDATE, 'MONTH') AS MONTH,
    TO_CHAR(SYSDATE, 'DD') AS DD,
    TO_CHAR(SYSDATE, 'DY') AS DY,
    TO_CHAR(SYSDATE, 'DAY') AS DAY
FROM DUAL;
-- 6-35 여러 언어로 날짜 출력하기
SELECT SYSDATE,
    TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = KOREAN') AS MON_KOR,
    TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = JAPANESE') AS MON_JPN,
    TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = ENGLISH') AS MON_ENG,
    TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = KOREAN') AS MONTH_KOR,
    TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = JAPANESE') AS MONTH_JPN,
    TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = ENGLISH') AS MONTH_ENG
FROM DUAL;
-- 6-36 여러 언어로 날짜(요일) 출력하기
SELECT SYSDATE,
    TO_CHAR(SYSDATE, 'MM') AS MM,
    TO_CHAR(SYSDATE, 'DD') AS DD,
    TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE = KOREAN') AS DY_KOR,
    TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE = JAPANESE') AS DY_JPN,
    TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE = ENGLISH') AS DY_ENG,
    TO_CHAR(SYSDATE, 'DAY', 'NLS_DATE_LANGUAGE = KOREAN') AS DAY_KOR,
    TO_CHAR(SYSDATE, 'DAY', 'NLS_DATE_LANGUAGE = JAPANESE') AS DAY_JPN,
    TO_CHAR(SYSDATE, 'DAY', 'NLS_DATE_LANGUAGE = ENGLISH') AS DAY_ENG
FROM DUAL;
-- 6-37 SYSDATE 시간 형식 지정하여 출력하기
SELECT SYSDATE,
    TO_CHAR(SYSDATE, 'HH24:MI:SS') AS HH24MISS,
    TO_CHAR(SYSDATE, 'HH12:MI:SS AM') AS HH12MISS_AM,
    TO_CHAR(SYSDATE, 'HH12:MI:SS AM', 'NLS_DATE_LANGUAGE = JAPANESE') AS HHMISS_AM,
    TO_CHAR(SYSDATE, 'HH:MI:SS P.M.') AS HHMISS_PM    
FROM DUAL;
-- 6-38 여러 숫자 형식으로 급여 출력
SELECT SAL,
    TO_CHAR(SAL, '$999,999') AS SAL_$,
    TO_CHAR(SAL*1288.33, 'l9,999,999') AS SAL_L,
    TO_CHAR(SAL, '999,999.00') AS SAL_1,
    TO_CHAR(SAL, '000,999,999.00') AS SAL_2,
    TO_CHAR(SAL, '000999999.99') AS SAL_3,
    TO_CHAR(SAL, '999,999,00') AS SAL_4
FROM EMP;
-- 6-39
SELECT 1300 - '1500', '1300'+1500 FROM DUAL;
-- 6-40
SELECT '1,300' - '1,500' FROM DUAL;
-- 6-41
SELECT TO_NUMBER('1,300', '999,999') - TO_NUMBER('1,500', '999,999') FROM DUAL;
-- 6-42 TO_DATE 문자데이터를 날짜 데이터로 변환
SELECT TO_DATE('2018-07-14', 'YYYY-MM-DD') AS TODATE1,
    TO_DATE('20180714', 'YYYY-MM-DD') AS TODATE2
FROM DUAL;
-- 6-43 1981년 6월 1일 이후 입사자 정보 출력
SELECT * FROM EMP
WHERE HIREDATE > TO_DATE('1981-06-01', 'YYYY-MM-DD');
-- 6-44 여러 형식의 날짜 출력
SELECT TO_DATE('49/12/10', 'YY/MM/DD') AS YY_YEAR_49,
    TO_DATE('49/12/10', 'RR/MM/DD') AS RR_YEAR_49,
    TO_DATE('50/12/10', 'YY/MM/DD') AS YY_YEAR_50,
    TO_DATE('50/12/10', 'RR/MM/DD') AS RR_YEAR_50,
    TO_DATE('51/12/10', 'YY/MM/DD') AS YY_YEAR_50,
    TO_DATE('51/12/10', 'RR/MM/DD') AS RR_YEAR_50
FROM DUAL;

